### PR TITLE
Rework argfile generation

### PR DESCRIPTION
**Pull request by melix**
Fixes the fact that paths may contain spaces.

Relates to https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/401

### CODE REVIEW

**Comment by alvarosanchez** [comment]
@melix I think escaping also needs to be done here: https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java#L270

**Comment by alvarosanchez** [comment]
@melix I think escaping also needs to be done here: https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java#L270

**Comment by melix** [comment]
> @melix I think escaping also needs to be done here: https://github.com/graalvm/native-build-tools/blob/master/native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java#L270

If I understand correctly, the intent of that line was to support multiple build arguments in a single call, say "-X -Y" should be split to "-X", "-Y". There shouldn't be escaping for build arguments, as those are _extra free arguments_. They shouldn't duplicate arguments which are handled directly by the plugin, like `-cp`.

**Comment by alvarosanchez** [comment]
You are probably right 👍

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
