### PR TITLE
maven-toolchains-plugin support for nativeImageExecutable

### PR DESCRIPTION
**Pull request by linux-china**
Find native-image binary from JDK Toolchain https://maven.apache.org/plugins/maven-toolchains-plugin/toolchains/jdk.html

### CODE REVIEW

**Comment by lazar-mitrovic** [comment]
@gilles-duboscq can you help with fixing a bot here? It returns a wrong url (it should be https://oca.opensource.oracle.com/)

Correct me if I'm wrong, but I believe that it should be OK if @linux-china registeres as a SVM (Native Image) contributor?

**Comment by gilles-duboscq** [comment]
@sanzinger, when was the update of the URLs deployed? could this be an old message? or did the bot get reset to the old address?

Regarding the project if there is SVM in the list that's fine. Otherwise there might be GraalVM. In any case one OCA covers all Oracle projects.

**Comment by linux-china** [comment]
@lazar-mitrovic   my email libing -(dot)- chen -(at)- gmail -(dot)- com. is "Under Review"  for github user "linux-china" now.

**Comment by linux-china** [comment]
@lazar-mitrovic  if still not lucky to get signed, and you can take a look at #143  and implement the feature.  It's just several lines :).

**Comment by lazar-mitrovic** [comment]
@linux-china Since you are working at Alibaba you should be under company-wide OCA if you commit using your `@alibaba.com` mail. 

As for your personal account, it seems that it isn't present here: https://oca.opensource.oracle.com/?ojr=contrib-list

**Comment by linux-china** [comment]
@lazar-mitrovic  could you implement this feature?   Company Agreement is some complicated for me, and it will be a long time for approval.  :)   I will close this PR later.

**Comment by sdeleuze** [comment]
Toolchain support is tricky and can have various side effect as we have seen on Gradle side, so I prefer to wait Graddle tooclhain is fully fixed before introducing anything on Maven side.

**Comment by linux-china** [comment]
Close this PR, and it works now with Maven 3.8.4 and maven-toolchains-plugin 3.0.0

```
 <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-toolchains-plugin</artifactId>
    <version>3.0.0</version>
    <executions>
        <execution>
            <goals>
                <goal>toolchain</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <toolchains>
            <jdk>
                <version>21.3</version>
                <vendor>graalvm_ce17</vendor>
            </jdk>
        </toolchains>
    </configuration>
 </plugin>

```

**Pull request closed without merging**
