### PR TITLE
Add metadata archives for testing remote repositories

### PR DESCRIPTION
**Pull request by alvarosanchez**
Required for #240 

The contents of the archives are:

```
index.json
org/
org/graalvm/
org/graalvm/internal/
org/graalvm/internal/library-with-reflection/
org/graalvm/internal/library-with-reflection/index.json
org/graalvm/internal/library-with-reflection/1/
org/graalvm/internal/library-with-reflection/1/reflect-config.json
```

### CODE REVIEW

**Comment by melix** [comment]
I don't think we should do this. Introducing archives in the repository isn't great since they are opaque and could be hacked. The approach taken by the `org.graalvm.buildtools.gradle.NativeConfigRepoFunctionalTest` is to create those archives _on demand_ during the test.

**Comment by alvarosanchez** [comment]
I already did that in #240

This is to test remote repositories and HTTP downloads.

**Comment by melix** [comment]
Still, if we need an archive then the build should be responsible for building it. Ideally, we don't even need this and can test with a pre-release of the metadata repo.

**Comment by alvarosanchez** [comment]
Closed in favour of [`731b768` (#240)](https://github.com/graalvm/native-build-tools/pull/240/commits/731b7687f8589e64548529e4807e8f263d3611ab)

**Pull request closed without merging**
