### PR TITLE
Make it possible to pass env vars to the builder process

### LINKED ISSUE #275: Gradle plugin doesn't support environment variables
The Gradle plugin, unlike the Maven one, doesn't let the user pass specific environment variables. This prevents, for example, from passing the `USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM` variable to the builder.

### PR DESCRIPTION
**Pull request by melix**
Fixes #275

### CODE REVIEW

**Review by alvarosanchez — APPROVED** [review]

**Comment by melix** [comment]
No idea why the maven tests are failing, when I obviously didn't change the Maven plugin :thinking:

**Comment by alvarosanchez** [comment]
I see this in the logs:

```
    [main] WARN org.codehaus.plexus.PlexusContainer - The POM for org.graalvm.buildtools:native-maven-plugin:jar:0.9.13-SNAPSHOT is missing, no dependency information available
    [main] WARN org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver - Failed to retrieve plugin descriptor for org.graalvm.buildtools:native-maven-plugin:0.9.13-SNAPSHOT: Plugin org.graalvm.buildtools:native-maven-plugin:0.9.13-SNAPSHOT or one of its dependencies could not be resolved: org.graalvm.buildtools:native-maven-plugin:jar:0.9.13-SNAPSHOT was not found in file:/home/runner/work/native-build-tools/native-build-tools/native-maven-plugin/build/maven-seeded-repo during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of seed has elapsed or updates are forced
    [main] WARN org.codehaus.plexus.PlexusContainer - The POM for org.graalvm.buildtools:native-maven-plugin:jar:0.9.13-SNAPSHOT is missing, no dependency information available
    [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
    [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - BUILD FAILURE
    [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
```

Seems there is an old 0.9.13-SNAPSHOT being referenced somewhere?

**Comment by melix** [comment]
ooohhh, very good catch @alvarosanchez ! https://github.com/graalvm/native-build-tools/pull/280/commits/67fa33998d941eb01fa37598bccb7456b2bb79aa

**Comment by lazar-mitrovic** [comment]
It seems that you need to add 
```xml
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>${maven.native.plugin.version}</version>
            </plugin>
```
to `samples/java-application-with-custom-packaging/pom.xml` in order to override plugin version (or at least that worked for me locally)

**Pull request merged**
