### PR TITLE
Bug fixes and improvements for GraalVM for JDK 21.

### PR DESCRIPTION
**Pull request by fniephaus**
Note: We need to run with `--strict-image-heap` enabled on GraalVM dev builds / GraalVM for JDK 21 in the future. The current dev build does not have the option, but has `--strict-image-heap` enabled by default.

### CODE REVIEW

**Comment by olpaw** [comment]
AFAIU we do not want end-users to use the version of NBTs that has this change. This is just for our own testing until time is right to switch to a GraalVM native-image where `--strict-image-heap` is the default.

**Comment by fniephaus** [comment]
> AFAIU we do not want end-users to use the version of NBTs that has this change. This is just for our own testing until time is right to switch to a GraalVM native-image where --strict-image-heap is the default. Correct?

We want users of GraalVM for JDK 21 to adopt `--strict-image-heap` as soon as possible, so support for it in NBT is necessary if you ask me. On the other hand, the additional build-time init policies should still work as before without `--strict-image-heap`: they are just complementary policies that we didn't know were actually needed. But yes, we should probably test this to be on the safe side.

**Comment by fniephaus** [comment]
> But yes, we should probably test this to be on the safe side.

Here's one way to test this now: https://github.com/graalvm/native-build-tools/commit/f7d1eb6d73d5a62ab1bb956725f10122307cfd3b

**Comment by olpaw** [comment]
> > But yes, we should probably test this to be on the safe side.
> 
> Here's one way to test this now: [f7d1eb6](https://github.com/graalvm/native-build-tools/commit/f7d1eb6d73d5a62ab1bb956725f10122307cfd3b)

Ok, this proves that the new JUnit init-at-build-/run-time condigs have no side effect when `--strict-image-heap` is off.

Sounds safe enough for me.

**Review by olpaw — APPROVED** [review]

**Comment by fniephaus** [comment]
It seems this is blocking the Micronaut Gradle plugin release: https://github.com/micronaut-projects/micronaut-starter/pull/2045#issuecomment-1717275538

**Pull request merged**
